default:
  auth:
    client:
      id: {{.CLIENT_ID}}
      secret: {{.CLIENT_SECRET}}
    password: {{.USER_PASSWORD}}
    type: password
    username: {{.USER_NAME}}
  domain: {{.DEV_DOMAIN}}
  http: https
  store:
    type: file
  tenant: {{.TEST_TENANT}}
local:
  auth:
    password: {{.USER_PASSWORD}}
    type: password
    username:  {{.USER_NAME}}
  domain: {{.LOCAL_DOMAIN}}
  http: http
  tenant: {{.TEST_TENANT}}
