default:
  auth:
    securePassword: ChboJPfebWr2YaYtCVLrWGC67TBroPYXyTEkN3Ry/Q9VfKVMCRvQY5qUARXu2A==
    type: password
    username: [INIT_USERNAME]
  cache:
    age: 5
    strategy: server.cache
  domain: [INIT_DEV_DOMAIN]
  store:
    type: file
  tenant: [INIT_TENANT]
