default:
  auth:
    securePassword: ChboJPfebWr2YaYtCVLrWGC67TBroPYXyTEkN3Ry/Q9VfKVMCRvQY5qUARXu2A==
    type: password
    username: [INIT_USERNAME]
  cache:
    strategy: server
  domain: secretsvaultcloud.com
  store:
    type: file
  tenant: [INIT_TENANT]
