---
name: auto-update-contributors
on:
  schedule:
    - cron: 30 1 * * *
  workflow_call:
  workflow_dispatch:
permissions:
  pull-requests: write
  contents: write
jobs:
  auto-update-contributors:
    uses: delineaxpm/github-workflows/.github/workflows/auto-update-contributors.yml@main
    secrets: inherit
