name: Go

on:
  workflow_dispatch:
  # temporarily disabled while migration/update work is performed on repo
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18.4
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.4'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod tidy

      - name: Build
        run: go build -v .

      - name: Test
        run: go test $(go list ./... | grep -v cicd-integration) -v
